### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chenkaixin66** [xuuuluuu/Aspect-Sentiment-Classification#1]
Why the epoch behind does not output the result？

**Comment by xuuuluuu** [comment]
Note that we used the best model that is selected based on the dev results. When there is no better performance on the dev set, it will not output the results.

**Comment by chenkaixin66** [comment]
> Note that we used the best model that is selected based on the dev results. When there is no better performance on the dev set, it will not output the results.

Thank you for your reply。 I have another question. How do I get the two pkl files contained in the vocab under data on other dataset? What do they mean?

**Comment by xuuuluuu** [comment]
Hi, we used GloVe for the word embedding, and the .pkl files are the saved vocabs based on the GloVe embedding. 

With these two files, we saved some time by not loading the huge original GloVe file every time when runnning the script.

**Comment by chenkaixin66** [comment]
> 
Thank you!
What do the above dict.pkl and local_emb.pkl mean, and what role do they play in the data? What is the difference with train.pkl below?
nn.Embdding is also used in the SimpleCat class defined in Layer.py

**Comment by xuuuluuu** [comment]
Hi, 
The dict.pkl and local_emb.pkl should be the saved vocab and embeddings. The train.pkl is the training data. You can load the files and check what are inside. 

nn.Embedding is created for the target embedding.

**Comment by chenkaixin66** [comment]
> Hi, The dict.pkl and local_emb.pkl should be the saved vocab and embeddings. The train.pkl is the training data. You can load the files and check what are inside.
> 
> nn.Embedding is created for the target embedding.

I Know,thank you very much
